[build-system]
requires = ["setuptools",
            "numpy; sys_platform == 'win32' and python_version < '3.12'",
            "Cython>=3"]
build-backend = "setuptools.build_meta"

[project]
name = "python-flint"
description = "Bindings for FLINT and Arb"
version = "0.6.0"
urls = {Homepage = "https://github.com/flintlib/python-flint"}
authors = [
    {name = "Fredrik Johansson", email = "fredrik.johansson@gmail.com"},
]
license = {text = "MIT"}
classifiers = [
    "Topic :: Scientific/Engineering :: Mathematics",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-* cp312-*"
skip = "*-win32 *-manylinux_i686 *-musllinux_*"
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
test-command = "python -c \"import flint; print(str(flint.fmpz(2)))\""

[tool.cibuildwheel.environment]
# bin/build_dependencies_unix.sh places headers and shared libraries under .local
C_INCLUDE_PATH = "$(pwd)/.local/include/"
LIBRARY_PATH = "$(pwd)/.local/lib/"
LD_LIBRARY_PATH = "$(pwd)/.local/lib:$LD_LIBRARY_PATH"

[tool.cibuildwheel.linux]
before-all = "bin/cibw_before_all_linux.sh"

[tool.cibuildwheel.macos]
before-all = "bin/cibw_before_all_macosx_$(uname -m).sh"

[tool.cibuildwheel.windows]
before-all = "C:\\msys64\\usr\\bin\\bash bin/cibw_before_all_windows.sh"
before-build = "pip install delvewheel && C:\\msys64\\usr\\bin\\bash bin/cibw_before_build_windows.sh"
repair-wheel-command = "bin\\cibw_repair_wheel_command_windows.bat {dest_dir} {wheel}"

[tool.cibuildwheel.windows.environment]
PYTHON_FLINT_MINGW64 = "true"
