name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-20.04, windows-2019, macOS-10.15]
        os: [ubuntu-20.04, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: cp37-* cp38-*
          CIBW_BEFORE_ALL_LINUX: bin/cibw_before_build_linux.sh
          CIBW_BEFORE_ALL_MACOS: bin/cibw_before_build_macosx.sh
          # There are problems with both older and newer cython versions...
          CIBW_BEFORE_BUILD: pip install numpy cython==0.27.3
          CIBW_ENVIRONMENT: >
            C_INCLUDE_PATH=$(pwd)/.local/include/
            LIBRARY_PATH=$(pwd)/.local/lib/
            LD_LIBRARY_PATH=$(pwd)/.local/lib:$LD_LIBRARY_PATH
      - uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl
